### ISSUE TITLE
Lines not breaking in code blocks

### ISSUE THREAD

**Issue by lucleray** [walle/mdpdf#1]
Hey,

When I generate a pdf from my markdown file,  the really long lines in code blocks are not completely appearing on the pdf.

There is a scrollbar, but it cannot be scrolled (obviously because it's a pdf).

<img width="961" alt="capture d ecran 2017-03-30 a 17 44 30" src="https://cloud.githubusercontent.com/assets/6616955/24513069/91e220fc-1570-11e7-8d52-0402b412f714.png">

**Comment by walle** [comment]
This is a css bug. The code and pre tags doesn't have proper wordwrap.

as a workaround you can create a new stylesheet with the following css and add it with the `--stylesheet`, `-s` flag.

```css
code, pre {
  white-space: pre;
  white-space: pre-wrap;
  word-break: break-all;
  word-wrap: break-word;
}
```

Alternatively patching the https://github.com/walle/mdpdf/blob/master/HTML_HEAD_START#L22 file and rebuild the application.

If you go with the patching, please submit a PR :)

Thanks for reporting!
